#!/bin/bash

echo "########## post_deploy ##########"

# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

(cd "${OPENSHIFT_REPO_DIR}"; export HOME=$OPENSHIFT_REPO_DIR; npm run build)
